requires "Kossy", 0.38;
requires "DBIx::Sunny";

requires "DBD::mysql";
requires "Starman";
requires "Plack::Session";
requires "Gazelle";
requires "Server::Starter";
requires "URL::Encode::XS";
requires "JSON::XS";
requires "Plack::Middleware::Session::Simple";
requires "Cache::Memcached::Fast";
requires "Sereal";
