- name: Install middleware
  tags: install
  hosts: all
  remote_user: isucon
  sudo: yes
  tasks:
    - apt:
        name: "{{item}}"
        update_cache: yes
        state: present
      with_items:
        - wget


- name: Upload Bench
  tags: install
  hosts: all
  remote_user: isucon
  tasks:
    - synchronize: src=home/bench dest=/home/isucon/
