- name: Install middlewares
  tags: install
  hosts: all
  remote_user: isucon
  sudo: yes
  tasks:
    - apt:
        name: "{{item}}"
        update_cache: yes
        state: present
      with_items:
        - wget
        - openjdk-8-jdk
        - jq
        - sysstat
        - libdbi-perl
        - percona-toolkit
        - memcached


- name: Upload Bench
  tags: install
  hosts: all
  remote_user: isucon
  tasks:
    - synchronize: src=home/bench dest=/home/isucon/ perms=yes


- name: Init settings
  tags: install
  hosts: all
  remote_user: isucon
  sudo: yes
  tasks:
    - user: name=isucon shell=/bin/bash
    - synchronize: src=server/etc/bashrc dest=/etc/bashrc
    - synchronize: src=home/.bashrc dest=./
      sudo: no
    - sysctl: name=net.ipv4.ip_local_port_range value="1024 65535" state=present
    - sysctl: name=net.ipv4.tcp_max_tw_buckets value="2000000" state=present
    - sysctl: name=net.core.somaxconn value="32768" state=present
    - sysctl: name=net.ipv4.tcp_tw_reuse value="1" state=present
    - sysctl: name=net.ipv4.tcp_tw_recycle value="1" state=present
    - sysctl: name=net.ipv4.tcp_fin_timeout value="10" state=present
    - sysctl: name=net.core.rmem_max value="16777216" state=present
    - sysctl: name=net.core.wmem_max value="16777216" state=present
    - sysctl: name=net.ipv4.tcp_rmem value="4096 87380 16777216" state=present
    - sysctl: name=net.ipv4.tcp_wmem value="4096 65536 16777216" state=present
    - sysctl: name=net.core.netdev_max_backlog value="30000" state=present
    - sysctl: name=net.ipv4.tcp_no_metrics_save value=1 state=present
    - sysctl: name=net.ipv4.tcp_syncookies value=0 state=present
    - sysctl: name=net.ipv4.tcp_max_orphans value=65535 state=present
    - sysctl: name=net.ipv4.tcp_max_syn_backlog value=65535 state=present
    - sysctl: name=net.ipv4.tcp_synack_retries value=2 state=present
    - sysctl: name=net.ipv4.tcp_syn_retries value=2 state=present
