- name: Setting Up middlewares
  tags: setting
  hosts: all
  remote_user: isucon
  sudo: yes
  tasks:
    - service: name=isuxi.ruby.service state=stopped 
    - synchronize:
        src: server/etc/systemd/system/isuxi.perl.service
        dest: /etc/systemd/system/isuxi.perl.service
      notify: Restart isuxi
    - name: Nginx conf
      synchronize:
        src: server/etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx

  handlers:
    - name: Restart isuxi
      service: name=isuxi.perl.service state=restarted
    - name: Restart nginx
      service: name=nginx state=restarted
