- name: Setting Up middlewares
  hosts: all
  remote_user: isucon
  sudo: yes
  tasks:
    - name: Mysql config
      synchronize:
        src: server/etc/mysql/mysql.conf.d/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      notify:
        - Restart mysql
        - Restart isuxi
      tags: mysql

    - name: Nginx conf
      synchronize:
        src: server/etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx
      tags: nginx

    - service: name=isuxi.ruby.service state=stopped enabled=no
    - service: name=isuxi.perl.service state=started enabled=yes

    - name: Upload isuxi
      synchronize:
        src: home/webapp/perl/
        dest: /home/isucon/webapp/perl
      notify: Restart isuxi
      sudo: no
      tags: isuxi

    - name: Upload isuxi.perl.service
      synchronize:
        src: server/etc/systemd/system/isuxi.perl.service
        dest: /etc/systemd/system/isuxi.perl.service
      notify:
        - Reload daemon
        - Restart isuxi
      tags: service


  handlers:
    - name: Restart mysql
      service: name=mysql state=restarted

    - name: Reload daemon
      command: systemctl daemon-reload

    - name: Restart isuxi
      service: name=isuxi.perl.service state=restarted

    - name: Restart nginx
      service: name=nginx state=restarted

