- name: Setting Up middlewares
  hosts: all
  remote_user: isucon
  sudo: yes
  tasks:
    - sysctl: name=net.ipv4.ip_local_port_range value="1024 65535" state=present
    - sysctl: name=net.ipv4.tcp_max_tw_buckets value="2000000" state=present
    - sysctl: name=net.core.somaxconn value="32768" state=present
    - sysctl: name=net.ipv4.tcp_tw_reuse value="1" state=present
    - sysctl: name=net.ipv4.tcp_tw_recycle value="1" state=present
    - sysctl: name=net.ipv4.tcp_fin_timeout value="10" state=present
    - name: Mysql config
      synchronize:
        src: server/etc/mysql/mysql.conf.d/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      notify:
        - Restart mysql
        - Restart isuxi
      tags: mysql

    - name: Nginx conf
      synchronize:
        src: server/etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx
      tags: nginx

    - service: name=isuxi.ruby.service state=stopped

    - name: Upload cpanfile
      synchronize:
        src: home/webapp/perl/cpanfile
        dest: /home/isucon/webapp/perl/cpanfile
      notify:
        - Carton install
        - Restart isuxi
      sudo: no
      tags: isuxi

    - name: Upload isuxi
      synchronize:
        src: home/webapp/perl/
        dest: /home/isucon/webapp/perl
      notify: Restart isuxi
      sudo: no
      tags: isuxi

    - name: Upload isuxi.perl.service
      synchronize:
        src: server/etc/systemd/system/isuxi.perl.service
        dest: /etc/systemd/system/isuxi.perl.service
      notify: Restart isuxi
      tags: service


  handlers:
    - name: Restart mysql
      service: name=mysql state=restarted

    - name: Restart isuxi
      service: name=isuxi.perl.service state=restarted

    - name: Restart nginx
      service: name=nginx state=restarted

    - name: Carton install
      sudo: no
      shell: /bin/bash -lc "carton install"
      args:
        chdir: webapp/perl
      notify: Restart isuxi
